title: TwTube
description: Brings the Video.js Media Player to TiddlyWiki 5.
google_analytics:
show_downloads: false
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/TheDiveO/TwTube/zipball/master
  tar_url: https://github.com/TheDiveO/TwTube/tarball/master
project_downloads:
  twtube_plugin:
    description: "TwTube plugin"
    url: output/twtube.tid
  iplayer_skin:
    description: "iPlayer-inspired skin"
    url: output/iplayerskin.tid
  sublimeskin:
    description: "Sublime-inspired skin"
    url: output/sublimeskin.tid
  ytskin:
    description: "YouTube-inspired skin"
    url: output/ytskin.tid
  videojshotkey_plugin:
    description: "Hotkey Video.js plugin"
    url: output/videojshotkeys.tid
gems:
  - jekyll-mentions
