title: TwTube
description: Brings the Video.js Media Player to TiddlyWiki5.
google_analytics:
show_downloads: true
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/TheDiveO/TwTube/zipball/master
  tar_url: https://github.com/TheDiveO/TwTube/tarball/master
project_downloads:
  twtube_plugin
    description: TwTube plugin
    url: output/twtube.tid
  demo
    description: TwTube demo wiki
    url: output/twtube.html
gems:
  - jekyll-mentions
