#!/bin/sh
#
# release
#
# generates release files:
#   editions\release\output\twtube.html -- the plugin demo wiki
#   editions\release\output\twtube.tid -- the plugin tiddler
#
tiddlywiki \
	editions/release \
	--verbose \
	--build release
